### PR TITLE
Updated Frameworks.md 

### PR DESCRIPTION
**Pull request by Drivez**
Added some info about Laravel

### CODE REVIEW

**Comment by mananpal1997** [comment]
@Drivez laravel image url is broken or not correct in the Framewrks.md
``

Can you update it and squash your commit?

Regards

**Comment by Drivez** [comment]
The image is in the commit, won't the link work after it is committed? then the image is at the right location in this repo?

**Comment by mananpal1997** [comment]
@Drivez the file at url `https://github.com/gabru-md/DevBible/blob/master/assets/laravel.png?raw=true` doesn't exist.
In your commit
```
### [Laravel](https://laravel.com/)
 +![Laravel](https://github.com/gabru-md/DevBible/blob/master/assets/laravel.png?raw=true)
 +
 +Laravel is a free, open-source PHP web framework, created by Taylor Otwell and intended for
...
```
the image doesn't render as there's nothing at that url (the url corresponds to gabru-md forked repo, rather than yours).
You can simply use `assets/laravel.png` , relative path. :smile:

**Comment by Drivez** [comment]
@mananpal1997 Thank you for the clarification, I did not know that. 👍

**Pull request merged**
