### PR TITLE
Updated Frameworks.md

### PR DESCRIPTION
**Pull request by gabru-md**
Added content about FLASK!  

:)

### CODE REVIEW

**Comment by mbad0la** [comment]
@mananpal1997 please review

**Comment by mananpal1997** [comment]
Seems fine to me. @mbad0la 
@gabru-md add sentdex too to tutorial list. I remember they too have nice flask tutorials. :smiley:

**Comment by mbad0la** [comment]
@mananpal1997 review and (squash and) merge if good. Refer git history for commit name.

**Comment by gabru-md** [comment]
images corresponding to different frameworks have been added.

**Pull request merged**
